
# Site settings

title: 窗外蟋蟀
SEOTitle: 窗外蟋蟀的博客 | Keysaim Blog
header-img: img/home-bg-hill.jpg
email: sun1741687725@gmail.com
description: "描述"
keyword: "窗外蟋蟀, keysaim"
url: "https://Syunach.github.io"
baseurl: ""
...
